version: '3.5'

services:

  dock: # Build the Dock with HDMI out and USB in...
    privileged: true
    build:
        context: .
        dockerfile: Dockerfile
        args:
            BOARD: lichee_rv_dock
            DISK_MB: 7300
            GNU_TOOLS_TAG: 10.2.1
            UBOOT_TAG: d1-wip
            KERNEL_TAG: d1/wip
            KERNEL_COMMIT: "ca67838d84af4c9f85d06311c9e98e1adf46308f"
    volumes:
        - './lichee_rv_dock:/outport'

  panel:
    privileged: true
    build:
        context: .
        dockerfile: Dockerfile
        args:
            BOARD: lichee_rv_86
            DISK_MB: 7300
            GNU_TOOLS_TAG: 10.2.1
            UBOOT_TAG: d1-2022-10-31
            KERNEL_TAG: d1-wip-v5.18-rc1
            KERNEL_COMMIT: ""
    volumes:
        - './lichee_rv_86:/outport'

  #lcd:  # Build the Dock with LCD display enabled
    #privileged: true
    #build:
        #context: .
        #dockerfile: Dockerfile
        #args:
            #BOARD: lichee_rv_lcd
            #DISK_MB: 8000
            #GNU_TOOLS_TAG: 10.2.1
            #UBOOT_TAG: d1-2022-10-31
            #KERNEL_TAG: d1-wip-v5.18-rc1
            #KERNEL_COMMIT: b466df9
    #volumes:
        #- './lichee_rv_lcd:/outport'
